import localFont from "next/font/local";
import "./globals.css";
import styles from './styles/RootLayout.module.css';
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Lab 10 20500",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <nav className={styles.nav}>
      <ul className={styles.navList}>
        <li className={styles.navItem}><Link className={styles.navLink} href="/">O mnie</Link></li>
        <li className={styles.navItem}><Link className={styles.navLink} href="/interests">Zainteresowania</Link></li>
        <li className={styles.navItem}><Link className={styles.navLink} href="/favoritegame">Ulubiona Gra</Link></li>
        <li className={styles.navItem}><Link className={styles.navLink} href="/contact">Kontakt</Link></li>
      </ul>
    </nav>

      {children}
    </body>
    </html>
  );
}
